spring.application.name=habitforge

spring.datasource.url=jdbc:mysql://localhost:3306/habitforge
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
spring.security.user.name=user
spring.security.user.password=password

habit.reminder.check-interval=${HABITFORGE_REMINDER_CHECK_INTERVAL:10000}
habit.reminder.timezone=${HABITFORGE_TIMEZONE:Asia/Kolkata}
habit.desktop-notification.enabled=${HABITFORGE_DESKTOP_NOTIFICATION_ENABLED:true}
habit.push.subject=${HABITFORGE_PUSH_SUBJECT:mailto:habitforge@example.com}
habit.push.public-key=BLGxcTcPOoWyenusPz-pf3JKYNeiOGMCVghGZCJws1V1_dVgkWsyyrXw_OKiPgPT9DxTrgavXoaRq_JphmYEXlg
habit.push.private-key=keRIW5qP9JkbAfQjgzgFJNR5X2BiMV2LKHau8VwSJTM

